### ISSUE TITLE
Tract analysis fails, looks for Latitude, Longitude columns

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/spatial-access#28]
While testing out the process I found that the even when the Census Tract ID Column is selected and the test data CSV with a tract id column is uploaded, the process fails with a message indicating that it is still looking for Lat/Long columns.

![image](https://github.com/healthyregions/spatial-access/assets/10427268/34197162-fa25-4234-ba43-ccef7e28d2b9)

![image](https://github.com/healthyregions/spatial-access/assets/10427268/5e46f35a-2736-4245-8d9f-ad06effcdc46)

BTW it is very good to have this test data to work with, though I noticed that this `tracts2010.csv` has lat/long columns, which I think should be removed just for the sake of clarity and simplicity (these column values also have a lot of leading spaces which is strange).

To complete:
- [x] #30
- [x] #29

**Comment by pengyin-shan** [comment]
@mradamcox thank you for checking this out, can you provide me the tracts2010.csv file you used?

**Comment by mradamcox** [comment]
Sure, it's the one in this repo here: https://github.com/healthyregions/spatial-access/tree/main/test_data
